serviceProperties :
    serviceDataProperties:
        serviceGroupName : "deploy"
        serviceName : "deploy_standalone"
        ip : "172.18.0.101"
        port : 8151
        rootUrl : "/deploy"
    zNodeInfoProperties:
        confZnodePath : "/confManageNode"
        deployChildZnodePath : "/confManageNode/deployManageNode"
        zookeeperHostport : "172.18.0.11:2191"

tomcatPort : 8151

logging.file : "/opt/deploy/log/console.log"